language: node_js

node_js:
  - 0.12
  - 4.2
  - 5.1

before_install:
  - npm install -g npm@latest
  - npm install -g git+https://github.com/gulpjs/gulp.git#4.0

install: npm install

before_script: gulp devel dist

notifications:
  email:
    recipients:
      - jmillan@aliax.net
      - ibc@aliax.net
      - saghul@gmail.com
    on_success: change
    on_failure: always
