# Doc: http://manuel.manuelles.nl/blog/2012/06/22/integrate-travis-ci-into-grunt/

language: node_js

node_js:
  - 0.10

before_install: npm install -g grunt-cli

install: npm install

# We want that Travis also checks the "devel" task.
before_script: grunt devel dist

notifications:
  email:
    recipients:
      - jmillan@aliax.net
      - ibc@aliax.net
      - saghul@gmail.com
    on_success: change
    on_failure: always
